from htmlthorapp.models import  Attribute

a = Attribute(aname="href", element_id=11, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="target", element_id=11, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="accesskey", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="class", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="contextmenu", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="dir", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="draggable", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="dropzone", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="hidden", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="id", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="spellcheck", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="style", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="tabindex", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="title", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="translate", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="crossorigin", element_id=69, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="hreflang", element_id=69, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="media", element_id=69, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="href", element_id=69, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="rel", element_id=69, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="sizes", element_id=69, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=69, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="charset", element_id=76, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="content", element_id=76, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="http-equiv", element_id=76, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="name", element_id=76, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=104, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="media", element_id=104, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="scoped", element_id=104, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="title", element_id=104, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=104, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="async", element_id=96, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="src", element_id=96, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=96, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="defer", element_id=96, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="onafterprint", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onbeforeprint", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onblur", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onerror", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onfocus", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onhashchange", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onload", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onmessage", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onoffline", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ononline", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onpopstate", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onredo", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onresize", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onstorage", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onundo", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onunload", element_id=18, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="cite", element_id=17, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="reversed", element_id=82, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="start", element_id=82, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=82, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=122, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=68, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="download", element_id=1, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="href", element_id=1, isGlobal=False, isRequired=True, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="hreflang", element_id=1, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="media", element_id=1, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="rel", element_id=1, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="target", element_id=1, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=1, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="cite", element_id=90, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=28, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="datetime", element_id=116, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="cite", element_id=62, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="datetime", element_id=62, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="cite", element_id=31, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="datetime", element_id=31, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="alt", element_id=60, isGlobal=False, isRequired=True, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="crossorigin", element_id=60, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="height", element_id=60, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="ismap", element_id=60, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="src", element_id=60, isGlobal=False, isRequired=True, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="width", element_id=60, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="usemap", element_id=60, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="allowfullscreen", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="height", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="name", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="sandbox", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="seamless", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="src", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="srcdoc", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="width", element_id=59, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="height", element_id=39, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="src", element_id=39, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=39, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="width", element_id=39, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="data", element_id=81, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="form", element_id=81, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="height", element_id=81, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="name", element_id=81, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=81, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="usemap", element_id=81, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="width", element_id=81, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="name", element_id=87, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=87, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autoplay", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="buffered", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="controls", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="crossorigin", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="height", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="loop", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="muted", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="played", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="preload", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="poster", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="src", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="width", element_id=124, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autoplay", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="buffered", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="controls", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="loop", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="muted", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="played", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="preload", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="src", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="volume", element_id=9, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="src", element_id=100, isGlobal=False, isRequired=True, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=100, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="media", element_id=100, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="default", element_id=119, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="kind", element_id=119, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="label", element_id=119, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="src", element_id=119, isGlobal=False, isRequired=True, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="srclang", element_id=119, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="width", element_id=21, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="height", element_id=21, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="alt", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="coords", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="download", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="href", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="hreflang", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="media", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="rel", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="shape", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="target", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=6, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="span", element_id=26, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="span", element_id=27, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="colspan", element_id=111, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="headers", element_id=111, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="rowspan", element_id=111, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="abbr", element_id=114, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="align", element_id=114, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="axis", element_id=114, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="colspan", element_id=114, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="headers", element_id=114, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="rowspan", element_id=114, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="scope", element_id=114, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="accept-charset", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="action", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autocomplete", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="enctype", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="method", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="name", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="novalidate", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="target", element_id=45, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=40, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="form", element_id=40, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="aname", element_id=40, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="accesskey", element_id=66, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="for", element_id=66, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="form", element_id=66, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="accept", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autocomplete", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autofocus", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="autosave", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="checked", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="form", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formaction", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formenctype", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formmethod", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formnovalidate", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="formtarget", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="height", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="inputmode", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="list", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="max", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="maxlength", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="min", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="multiple", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="name", element_id=61, isGlobal=False, isRequired=True, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="pattern", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="placeholder", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="readonly", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="required", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="selectionDirection", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="size", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="spellcheck", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="src", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="step", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=61, isGlobal=False, isRequired=True, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="width", element_id=61, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autofocus", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="form", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formaction", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formenctype", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formmethod", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="formnovalidate", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="formtarget", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="name", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=20, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autofocus", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="form", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="multiple", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="selectedIndex", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="aname", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="required", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="size", element_id=98, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=83, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="label", element_id=83, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=84, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="label", element_id=84, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="selected", element_id=84, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="value", element_id=84, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autofocus", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="cols", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="form", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="maxlength", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="aname", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="placeholder", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="required", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="rows", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="selectionDirection", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="selectionEnd", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="selectionStart", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="spellcheck", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="wrap", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="autofocus", element_id=65, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="challenge", element_id=65, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=65, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="form", element_id=65, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="keytype", element_id=65, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="aname", element_id=65, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="for", element_id=85, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="form", element_id=85, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="name", element_id=85, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="max", element_id=89, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=89, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="value", element_id=77, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="min", element_id=77, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="max", element_id=77, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="low", element_id=77, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="high", element_id=77, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="optimum", element_id=77, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="form", element_id=77, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="open", element_id=32, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="checked", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="command", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="default", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="disabled", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="icon", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="label", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="radiogroup", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=75, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="type", element_id=74, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="label", element_id=74, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="lang", element_id=57, isGlobal=False, isRequired=False, isDeprecated=True, isBoolean=False, isScript=False)
a.save()
a = Attribute(aname="readonly", element_id=112, isGlobal=False, isRequired=False, isDeprecated=False, isBoolean=True, isScript=False)
a.save()
a = Attribute(aname="onblur", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onchange", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="oncontextmenu", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onfocus", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onformchange", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onforminput", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="oninput", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="oninvalid", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onreset", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onselect", element_id=0, isGlobal=True, isRequired=False, isDeprecated=True, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onsubmit", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onkeydown", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onkeypress", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onkeyup", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onclick", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondblclick", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondrag", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondragend", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondragcenter", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondragleave", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondragover", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondragstart", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondrop", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onmousedown", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onmousemove", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onmouseout", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onmouseover", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onmouseup", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onmousewheel", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onscroll", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onabort", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="oncanplay", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="oncanplaythrough", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ondurationchange", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onemptied", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onerror", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onloadeddata", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onloadedmetadata", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onloadstart", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onpause", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onplay", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onplaying", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onprogress", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onratechange", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onreadystatechange", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onseeked", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onseeking", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onstalled", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onsuspend", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="ontimeupdate", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onvolumechange", element_id=0, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="onwaiting", element_id=00, isGlobal=True, isRequired=False, isDeprecated=False, isBoolean=False, isScript=True)
a.save()
a = Attribute(aname="name", element_id=1, isGlobal=False, isRequired=False, isDeprecated=True, isBoolean=False, isScript=False)
a.save()
