from htmlthorapp.models import Error
from django.conf import settings

if not settings.configured:
	settings.configure()

e =  Error(message="You should only have one base tag in your html document, which belongs in the head.",errorType="SEM")
e.save()
e =  Error(message="Oops! It looks like something's wrong with your doctype. Make sure you've written it like this: <!DOCTYPE html>.",errorType="SYN")
e.save()
e =  Error(message="Hey, we can't find your doctype! Make sure you write it like this <!DOCTYPE html> on the first line of your HTML file.",errorType="SYN")
e.save()
e =  Error(message="Hey, we can't find your html tag! Make sure you write it under your doctype and finish it with a closing tag at the end of your document.",errorType="SYN")
e.save()
e =  Error(message="Hey, we can't find your head tag! The head's important for storing information for third parties like search engines. Make sure the head tag comes before your body.",errorType="SYN")
e.save()
e =  Error(message="Did you want to include a title for your awesome webpage? The <title> and </title> tags belong in the head of your document.",errorType="SYN")
e.save()
e =  Error(message="Hey, we can't find your body tag! The body's necessary because it is the basis for your webpage! Make sure your body tag comes right after your head tag.",errorType="SYN")
e.save()
e =  Error(message="You only need one <!DOCTYPE html>. This other doctype will mess up your html!",errorType="SEM")
e.save()
e =  Error(message="You only need one html tag to start your document (after the doctype) and one to close your document (at the very end). Here you've got an extra one too many!",errorType="SEM")
e.save()
e =  Error(message="This stray head tag is looking out of place - you may want to delete it. You only need one head for your html document, which belongs above the body.",errorType="SEM")
e.save()
e =  Error(message="<title>'s a deceiving little one! You only need one title in your document's head. If you want to make headings for your webpage, you may want to use the <h1> tag.",errorType="SEM")
e.save()
e =  Error(message="Hey your <base> tag belongs to the head of your document! Remember you only need one. Send it back home by placing it between your <head></head> tags.",errorType="SEM")
e.save()
e =  Error(message="Hey your <link> tag belongs to the head of your document! Send it back home by placing it between your <head></head> tags.",errorType="SEM")
e.save()
e =  Error(message="Hey your <meta> tag belongs to the head of your document! Send it back home by placing it between your <head></head> tags.",errorType="SEM")
e.save()
e =  Error(message="We can't find the closing --element_c tag! This has might cause a bunch of errors (below) to come up.. Go back and close this tag then revalidate your code",errorType="SYN")
e.save()
e =  Error(message="Hey your <body> tag belongs right after your closing </head> tag. The closing </body> tag belongs just before your closing </html> tag. Remember you only need one pair for your document!",errorType="SEM")
e.save()
e =  Error(message="Hey! Your <main> tag belongs only inside your <body> tags, it also needs a </main> tag, and should only exist once because it's like your content wrapper.",errorType="SEM")
e.save()
e =  Error(message="We don't know anything about the --tag tag. It does not exist in HTML. Make sure you've spelt the tag correctly!",errorType="SYN")
e.save()
e =  Error(message="Looks like you haven't self-closed your --element_uc tag by ending it like this />.",errorType="SYN")
e.save()
e =  Error(message="Your <style> tag seems to be missing a compulsory type="" attribute. ",errorType="SYN")
e.save()
e =  Error(message="Your <--tag> tag seems to be missing the compulsory --attr attribute.",errorType="SYN")
e.save()
e =  Error(message="We can't find this attribute! You've either spelt it wrong, or you're using an attribute that does not validly belong to this tag (or doesn't exist at all)!",errorType="SYN")
e.save()
e =  Error(message="is an attribute that does not exist for this tag. Make sure you've spelt it correctly or that you're not using the attribute which belongs to another tag!",errorType="SYN")
e.save()
e =  Error(message="Are you using <s> for deleted text? If so, you should be using <del> instead.",errorType="SEM")
e.save()
e =  Error(message="Are you using <i> for emphasised text? If so, you should use <em> instead. <i> should only be used for text that is offset from regular text but has no extra emphasis or importance (such as technical terms or foreign language phrases).",errorType="SEM")
e.save()
e =  Error(message="Are you using <b> for important text? If so, you should use <strong> instead. <b> should only be used for text that is stylistically different, but has no special importance (such as product names in a review, or keywords in a document ",errorType="SEM")
e.save()
e =  Error(message="Are you using <u> for underlined text? If so, you should only use it for specific types of text, such as text misspellings. As underlines are used for links, you should avoid using them when you can.",errorType="SEM")
e.save()
e =  Error(message ="Looks like you're using this div for a --semantic. How about using --element?" , errorType="SEM")
e.save()
e =  Error(message ="Looks like you're using a deprecated tag. The --element tag is no longer used in HTML." , errorType="DEP")
e.save()
e =  Error(message ="Looks like you're using a deprecated attribute. --attr is no longer used for --tag. It may have been replaced by a different attribute or just considered unnecessary" , errorType="DEP")
e.save()
e =  Error(message ="Looks like you have self closed your --element_uc tag by ending it like this '/>'. This tag is not allowed to close that way. Close it properly by adding '</--element_uc>'" , errorType="SEM")
e.save()
e =  Error(message ="You seem to be missing a charset declaration inside a <meta> tag. It helps the browser read your file! Add <meta charset'utf-8'/> inside your <heard> to help your favourite browser!" , errorType="SEM")
e.save()
e =  Error(message ="We suggest including a space before the closing '/'. This is not strictly required however" , errorType="WAR")
e.save()
e =  Error(message ="For best practices, use the value attribute for every <input> tag." , errorType="WAR")
e.save()
e =  Error(message ="For best practices, use the name attribute for every <input> tag." , errorType="WAR")
e.save()
e =  Error(message ="For best practices, use the alt attribute for every <img> tag to supply an alternative text description of the image." , errorType="WAR")
e.save()
e =  Error(message ="You have used at two <br /> tags in a row. If you are using br tags to create a list, use <li> tags instead. Otherwise use CSS to style your page, if you want to skip a few lines." , errorType="SEM")
e.save()
e =  Error(message ="Oops! --attval is the value of an attribute. All attribute values belong inside quotes. Fix it with --att='-attval'." , errorType="SEM")
e.save()
e =  Error(message =" is already used as an ID value earlier in the file. All IDs must be unique." , errorType="SEM")
e.save()
e =  Error(message ="We could not find --fp. Make sure you got the file path correct. Remember to use correct upper- and lower-case." , errorType="BRO")
e.save()
e =  Error(message ="The -attr attribute is a boolean attribute. That means simply by setting it, you are assigning a value to it. So no need explicitly assign a value. Please delete your = and value." , errorType="SYN")
e.save()
e =  Error(message ="Even though # is not required to be in quotes, it is considered best practice for consistency." , errorType="WAR")
e.save()
e =  Error(message ="-attr must have an associated value. Use -attr='value' to set a value to this attribute. Most attributes require values to be associated. Be careful though, there are a few which don't." , errorType="SYN")
e.save()
e =  Error(message =" has already been assigned once for this tag. Each attribute should only be used once for each tag!" , errorType="SYN")
e.save()
e =  Error(message ="You should only have one base tag in your html document, which belongs in the head." , errorType="SEM")
e.save()
e =  Error(message ="You only need to have one set of main tags, embedded just under your body tags." , errorType="SEM")
e.save()
e =  Error(message ="It's best to avoid using the main tag as it is not rendered consistently across major browsers." , errorType="WAR")
e.save()
e =  Error(message ="Whoops, your close tags are in the wrong order! The last tag opened should be the first one closed." , errorType="SYN")
e.save()
e =  Error(message ="Naughty! It looks like you're using an element within itself. This is not allowed for this element." , errorType="SEM")
e.save()
e =  Error(message ="Seems like this tag is in the wrong place! All table elements should be within a <table>." , errorType="SYN")
e.save()
e =  Error(message ="Seems like this tag is in the wrong place! All form elements should be within a <form>." , errorType="SYN")
e.save()
e =  Error(message ="You've left this guy stranded! All your elements should be contained within <html> tags." , errorType="SYN")
e.save()
e =  Error(message ="This tag is in the wrong section! This element is not valid for <head>." , errorType="SYN")
e.save()
e =  Error(message ="This tag is in the wrong section! This element is not valid for <body>." , errorType="SYN")
e.save()
e =  Error(message ="This element hasn't been closed! Remember to close all your open elements!" , errorType="SYN")
e.save()
e =  Error(message ="This closing tag doesn't have a start tag!" , errorType="SYN")
e.save()
e =  Error(message ="It looks like your table elements are not in the correct order! Ensure that <caption> is the first tag in your table if you have one." , errorType="SYN")
e.save()
e =  Error(message ="It looks like you have multiple instances of a singular table tag." , errorType="SYN")
e.save()
e =  Error(message ="Your table element is in the wrong type of table tag!" , errorType="SYN")
e.save()
